name: EnvGuard CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  validate-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Set and echo secrets and vars
        run: |
          echo "Secrets and Vars:"
          echo "$ALLMYSECRETS"
          echo "$ALLMYVARS"
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}

      - name: Run your command
        run: npm start -- --token=${{ secrets.ACT_GH }} --repo=${{ github.repository }} --schema=false
